
package webservice.tempuri.juzhuzheng.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResidenceInfo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResidenceInfo {


    /**
     * 
     * @param guid
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryByID", targetNamespace = "http://tempuri.org/", className = "webservice.tempuri.juzhuzheng.org.tempuri.QueryByID")
    @ResponseWrapper(localName = "queryByIDResponse", targetNamespace = "http://tempuri.org/", className = "webservice.tempuri.juzhuzheng.org.tempuri.QueryByIDResponse")
    public String queryByID(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param month
     * @param requestid
     * @param guid
     * @return
     *     returns java.lang.String
     */
/*    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryByMonth", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryByMonth")
    @ResponseWrapper(localName = "queryByMonthResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryByMonthResponse")
    public String queryByMonth(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "requestid", targetNamespace = "")
        String requestid,
        @WebParam(name = "month", targetNamespace = "")
        String month);*/

}
