
package webservice.tempuri.juzhuzheng.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResidenceInfo", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://hjpt.fjzwt.cn:9000/hjservice/ResidenceInfo?wsdl")
public class ResidenceInfo_Service
    extends Service
{

    private final static URL RESIDENCEINFO_WSDL_LOCATION;
    private final static WebServiceException RESIDENCEINFO_EXCEPTION;
    private final static QName RESIDENCEINFO_QNAME = new QName("http://tempuri.org/", "ResidenceInfo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hjpt.fjzwt.cn:9000/hjservice/ResidenceInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESIDENCEINFO_WSDL_LOCATION = url;
        RESIDENCEINFO_EXCEPTION = e;
    }

    public ResidenceInfo_Service() {
        super(__getWsdlLocation(), RESIDENCEINFO_QNAME);
    }

    public ResidenceInfo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESIDENCEINFO_QNAME, features);
    }

    public ResidenceInfo_Service(URL wsdlLocation) {
        super(wsdlLocation, RESIDENCEINFO_QNAME);
    }

    public ResidenceInfo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESIDENCEINFO_QNAME, features);
    }

    public ResidenceInfo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResidenceInfo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResidenceInfo
     */
    @WebEndpoint(name = "ResidenceInfoImplPort")
    public ResidenceInfo getResidenceInfoImplPort() {
        return super.getPort(new QName("http://tempuri.org/", "ResidenceInfoImplPort"), ResidenceInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResidenceInfo
     */
    @WebEndpoint(name = "ResidenceInfoImplPort")
    public ResidenceInfo getResidenceInfoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ResidenceInfoImplPort"), ResidenceInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESIDENCEINFO_EXCEPTION!= null) {
            throw RESIDENCEINFO_EXCEPTION;
        }
        return RESIDENCEINFO_WSDL_LOCATION;
    }

}
